packages:
  - .

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - sharp
  - supabase
  - unrs-resolver

patchedDependencies:
  better-auth@1.4.18: patches/better-auth@1.4.18.patch
